python3: fix issue with zipfile
The build of some Python packages (e.g.: setuptools) is failing with the
following error:

ValueError: ZIP does not support timestamps before 1980

Prevent that by forcing the date/time when (for some reason) the
timestamp is less than 1980.

Related-to: TOR-2122

Signed-off-by: Sergio Prado <sergio.prado@toradex.com>