Make sure DEFAULTTUNE is set for tordy distro
This make sure that TordyOS uses the same tunes as LMP again:
TUNE_FEATURES        = "arm armv7a vfp thumb neon callconvention-hard"

It seems to also fix obscure QA issues such as:
  ERROR: dbus-1.12.8-r0 do_package_qa: QA Issue: /usr/libexec/dbus-daemon-launch-helper contained in package dbus requires libdbus-1.so.3(LIBDBUS_PRIVATE_1.12.8), but no providers found in RDEPENDS_dbus? [file-rdeps]
  WARNING: dbus-1.12.8-r0 do_package_qa: QA Issue: dbus-dev rdepends on docker-disk, but it isn't a build dependency, missing docker-disk in DEPENDS or PACKAGECONFIG? [build-deps]
  WARNING: openssh-7.7p1-r0 do_package_qa: QA Issue: openssh-misc rdepends on docker-disk, but it isn't a build dependency, missing docker-disk in DEPENDS or PACKAGECONFIG? [build-deps]
  ERROR: dbus-1.12.8-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
  ERROR: dbus-1.12.8-r0 do_package_qa: Function failed: do_package_qa

Signed-off-by: Stefan Agner <stefan.agner@toradex.com>