systemd: do not define systemd-udev-rules package
systemd-udev-rules package is already defined in the systemd recipe, so
no need to redefine it in the append file.

This also avoids the following QA message:

ERROR: systemd-1_250.5-r0 do_package: QA Issue: systemd-udev-rules is
listed in PACKAGES multiple times, this leads to packaging errors.
[packages-list]

Related-to: TOR-2122

Signed-off-by: Sergio Prado <sergio.prado@toradex.com>