rac: fix QA issue on emulated targets
The package task is failing with the following QA issue on genericx86-64
and qemuarm64.

ERROR: rac-0.0+gitAUTOINC+7ecb91932a-r0 do_package_qa: QA Issue:
Architecture did not match (ARM, expected x86-64) in /usr/bin/rac [arch]

For qemuarm64, we just install the statically linked file for ARM64.

For genericx86-64, we ignore the error (we don't care much here since
this recipe will soon be replace by another one that will build rac from
sources).

Related-to: TOR-3004

Signed-off-by: Sergio Prado <sergio.prado@toradex.com>