image-common: use TEZI_IMAGE_NAME
Use TEZI_IMAGE_NAME instead of IMAGE_NAME. This avoids symlinks pointing
to themselves which cause issues on CI:
  OSError: [Errno 40] Too many levels of symbolic links:
  'images/qemuarm64/torizon-core-docker-qemuarm64.testdata.json'

Signed-off-by: Stefan Agner <stefan.agner@toradex.com>