ostree: fix deployment on the target
When devicetree directory support has been added, OSTree deployment on
the target has been broken. Deployment failed with the following error:
  error: Installing kernel: linkat(imx6q-apalis-eval.dtb): File exists

This patch fixes the issue by skipping existing file (the way single
devicetree support is doing it).

Related-to: TOR-581
Signed-off-by: Stefan Agner <stefan.agner@toradex.com>